.nh
.TH eza_colors-explanation(5) $version

.SH Name
eza_colors-explanation — more details on customizing eza colors


.SH Eza Color Explanation
eza provides its own built-in set of file extension mappings that cover a large range of common file extensions, including documents, archives, media, and temporary files.
Any mappings in the environment variables will override this default set: running eza with \fBLS_COLORS="*.zip=32"\fR will turn zip files green but leave the colours of other compressed files alone.

.PP
You can also disable this built-in set entirely by including a
\fBreset\fR entry at the beginning of \fBEZA_COLORS\fR\&.
So setting \fBEZA_COLORS="reset:*.txt=31"\fR will highlight only text
files; setting \fBEZA_COLORS="reset"\fR will highlight nothing.

.SH Examples
.IP \(bu 2
Disable the "current user" highlighting: \fBEZA_COLORS="uu=0:gu=0"\fR
.IP \(bu 2
Turn the date column green: \fBEZA_COLORS="da=32"\fR
.IP \(bu 2
Highlight Vagrantfiles: \fBEZA_COLORS="Vagrantfile=1;4;33"\fR
.IP \(bu 2
Override the existing zip colour: \fBEZA_COLORS="*.zip=38;5;125"\fR
.IP \(bu 2
Markdown files a shade of green, log files a shade of grey:
\fBEZA_COLORS="*.md=38;5;121:*.log=38;5;248"\fR

.SH BUILT-IN EXTENSIONS
.IP \(bu 2
eza now supports bright colours! As supported by most modern 256-colour terminals, you can now choose from \fBbright\fR colour codes when selecting your custom colours in your \fB#EZA_COLORS\fR environment variable.
.IP \(bu 2
Build (Makefile, Cargo.toml, package.json) are yellow and underlined.
.IP \(bu 2
Images (png, jpeg, gif) are purple.
.IP \(bu 2
Videos (mp4, ogv, m2ts) are a slightly purpler purple.
.IP \(bu 2
Music (mp3, m4a, ogg) is a faint blue.
.IP \(bu 2
Lossless music (flac, alac, wav) is a less faint blue.
.IP \(bu 2
Cryptographic files (asc, enc, p12) are bright green.
.IP \(bu 2
Documents (pdf, doc, dvi) are a fainter green.
.IP \(bu 2
Compressed files (zip, tgz, Z) are red.
.IP \(bu 2
Temporary files (tmp, swp, ~) are dimmed default foreground color.
.IP \(bu 2
Compiled files (class, o, pyc) are yellow. A file is also counted as compiled if it uses a common extension and is
in the same directory as one of its source files: styles.css will count as compiled when next to styles.less or styles.sass, and scripts.js when next to scripts.ts or scripts.coffee.
.IP \(bu 2
Source files (cpp, js, java) are bright yellow.

.SH Theme Configuration file
Now you can specify these options and more in a \fBtheme.yml\fR file with convenient syntax for defining your styles.

.PP
Set \fBEZA_CONFIG_DIR\fR to specify which directory you would like eza to look for your \fBtheme.yml\fR file,
otherwise eza will look for \fB$XDG_CONFIG_HOME/eza/theme.yml\fR\&.

.PP
These are the available options:


.SH LIST OF THEME OPTIONS
.EX
filekinds:
  normal
  directory
  symlink
  pipe
  block_device
  char_device
  socket
  special
  executable
  mount_point

perms:
  user_read
  user_write
  user_executable_file
  user_execute_other
  group_read
  group_write
  group_execute
  other_read
  other_write
  other_execute
  special_user_file
  special_other
  attribute

size:
  major
  minor
  number_byte
  number_kilo
  number_mega
  number_giga
  number_huge
  unit_byte
  unit_kilo
  unit_mega
  unit_giga
  unit_huge

users:
  user_you
  user_root
  user_other
  group_yours
  group_other
  group_root

links:
  normal
  multi_link_file

git:
  new
  modified
  deleted
  renamed
  ignored
  conflicted

git_repo:
  branch_main
  branch_other
  git_clean
  git_dirty

security_context:
  none:
  selinux:
    colon
    user
    role
    typ
    range

file_type:
  image
  video
  music
  crypto
  document
  compressed
  temp
  compiled
  build
  source

punctuation:

date:

inode:

blocks:

header:

octal:

flags:

control_char:

broken_symlink:

broken_path_overlay:

.EE

.PP
Each of those fields/sub fields can have the following styling properties defined beneath it

.EX
    foreground: Blue
    background: null
    is_bold: false
    is_dimmed: false
    is_italic: false
    is_underline: false
    is_blink: false
    is_reverse: false
    is_hidden: false
    is_strikethrough: true
    prefix_with_reset: false
.EE

.PP
Example:

.EX

file_type:
  image:
    foreground: Blue
    is_italic: true
date:
  foreground: White

security_context:
  selinux:
    role:
      is_hidden: true
.EE

.PP
Icons can now be customized as well in the \fBfilenames\fR and \fBextensions\fR fields

.EX

filenames:
  # Just change the icon glyph
  Cargo.toml: {icon: {glyph: 🦀}}
  Cargo.lock: {icon: {glyph: 🦀}}

extensions:
  rs: {  filename: {foreground: Red}, icon: {glyph: 🦀}}

.EE

.PP
\fBNOTES:\fP

.PP
Not all glyphs support changing colors.

.PP
If your theme is not working properly, double check the syntax in the config file, as
a syntax issue can cause multiple properties to not be applied.

.PP
You must name the file \fBtheme.yml\fR, no matter the directory you specify.

.SH See also
.IP \(bu 2

\[la]eza.1.md\[ra]
.IP \(bu 2

\[la]eza_colors.5.md\[ra]
